#!/bin/sh
set -e

cd "$(dirname "$0")/.."

echo "\n==> Running unit tests..."
CI=true ./bin/node-harmony-proxies ./bin/unit-tests

echo "\n==> Running acceptance tests..."
CI=true ./bin/acceptance-tests
